#ifndef _BUTTERFLYFISH_BUTTERFLYFISH_H_
#define _BUTTERFLYFISH_BUTTERFLYFISH_H_

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

#include <butterflyfish/collection_i.h>
#include <butterflyfish/collection_ni.h>
#include <butterflyfish/collection_s.h>
#include <butterflyfish/collection_i_i.h>
#include <butterflyfish/collection_ni_ni.h>
#include <butterflyfish/collection_s_s.h>
#include <butterflyfish/fixed_list_i.h>
#include <butterflyfish/fixed_list_ni.h>
#include <butterflyfish/fixed_list_s.h>
#include <butterflyfish/list_i.h>
#include <butterflyfish/list_ni.h>
#include <butterflyfish/list_s.h>
#include <butterflyfish/map_entry_i_i.h>
#include <butterflyfish/map_entry_ni_ni.h>
#include <butterflyfish/map_entry_s_s.h>
#include <butterflyfish/map_i_i.h>
#include <butterflyfish/map_ni_ni.h>
#include <butterflyfish/map_s_s.h>
#include <butterflyfish/ordered_map_i_i.h>
#include <butterflyfish/ordered_map_ni_ni.h>
#include <butterflyfish/ordered_map_s_s.h>
#include <butterflyfish/ordered_set_i.h>
#include <butterflyfish/ordered_set_ni.h>
#include <butterflyfish/ordered_set_s.h>
#include <butterflyfish/queue_i.h>
#include <butterflyfish/queue_ni.h>
#include <butterflyfish/queue_s.h>
#include <butterflyfish/reducible_list_i.h>
#include <butterflyfish/reducible_list_ni.h>
#include <butterflyfish/reducible_list_s.h>
#include <butterflyfish/set_i.h>
#include <butterflyfish/set_ni.h>
#include <butterflyfish/set_s.h>
#include <butterflyfish/sorted_map_i_i.h>
#include <butterflyfish/sorted_map_ni_ni.h>
#include <butterflyfish/sorted_map_s_s.h>
#include <butterflyfish/sorted_set_i.h>
#include <butterflyfish/sorted_set_ni.h>
#include <butterflyfish/sorted_set_s.h>
#include <butterflyfish/stack_i.h>
#include <butterflyfish/stack_ni.h>
#include <butterflyfish/stack_s.h>
#include <butterflyfish/stream_i.h>
#include <butterflyfish/stream_ni.h>
#include <butterflyfish/stream_s.h>
#include <butterflyfish/stream_i_i.h>
#include <butterflyfish/stream_ni_ni.h>
#include <butterflyfish/stream_s_s.h>

#endif /* _BUTTERFLYFISH_BUTTERFLYFISH_H_ */
